source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/sspAppTeam/SSSpecs.git'
use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!

target 'YJT_DriverManager_Example' do
  pod 'YJT_DriverManager', :path => '../'

  target 'YJT_DriverManager_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
    pod 'SSNetworkOC'
  end
end
